# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OCT.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 544)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setGeometry(QtCore.QRect(0, 0, 521, 531))
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.tab_main = QtWidgets.QTabWidget(self.frame_main)
        self.tab_main.setGeometry(QtCore.QRect(10, 10, 501, 511))
        self.tab_main.setObjectName("tab_main")
        self.tab_Xsec = QtWidgets.QWidget()
        self.tab_Xsec.setObjectName("tab_Xsec")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_Xsec)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_confocal = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_confocal.setContentsMargins(0, 0, 0, 0)
        self.grid_confocal.setObjectName("grid_confocal")
        self.btn_confocal_start = QtWidgets.QPushButton(self.tab_Xsec)
        self.btn_confocal_start.setGeometry(QtCore.QRect(10, 400, 51, 23))
        self.btn_confocal_start.setObjectName("btn_confocal_start")
        self.btn_confocal_stop = QtWidgets.QPushButton(self.tab_Xsec)
        self.btn_confocal_stop.setGeometry(QtCore.QRect(60, 400, 51, 23))
        self.btn_confocal_stop.setObjectName("btn_confocal_stop")
        self.dbl_confocal_x_start = QtWidgets.QDoubleSpinBox(self.tab_Xsec)
        self.dbl_confocal_x_start.setGeometry(QtCore.QRect(240, 410, 51, 22))
        self.dbl_confocal_x_start.setMinimum(-10.0)
        self.dbl_confocal_x_start.setMaximum(10.0)
        self.dbl_confocal_x_start.setProperty("value", -0.5)
        self.dbl_confocal_x_start.setObjectName("dbl_confocal_x_start")
        self.dbl_confocal_x_stop = QtWidgets.QDoubleSpinBox(self.tab_Xsec)
        self.dbl_confocal_x_stop.setGeometry(QtCore.QRect(240, 430, 51, 22))
        self.dbl_confocal_x_stop.setMinimum(-10.0)
        self.dbl_confocal_x_stop.setMaximum(10.0)
        self.dbl_confocal_x_stop.setProperty("value", 0.5)
        self.dbl_confocal_x_stop.setObjectName("dbl_confocal_x_stop")
        self.int_confocal_x_numsteps = QtWidgets.QSpinBox(self.tab_Xsec)
        self.int_confocal_x_numsteps.setGeometry(QtCore.QRect(240, 450, 51, 22))
        self.int_confocal_x_numsteps.setMaximum(2048)
        self.int_confocal_x_numsteps.setProperty("value", 500)
        self.int_confocal_x_numsteps.setObjectName("int_confocal_x_numsteps")
        self.dbl_confocal_y_start = QtWidgets.QDoubleSpinBox(self.tab_Xsec)
        self.dbl_confocal_y_start.setGeometry(QtCore.QRect(300, 410, 51, 22))
        self.dbl_confocal_y_start.setObjectName("dbl_confocal_y_start")
        self.dbl_confocal_y_stop = QtWidgets.QDoubleSpinBox(self.tab_Xsec)
        self.dbl_confocal_y_stop.setGeometry(QtCore.QRect(300, 430, 51, 22))
        self.dbl_confocal_y_stop.setObjectName("dbl_confocal_y_stop")
        self.int_confocal_y_numsteps = QtWidgets.QSpinBox(self.tab_Xsec)
        self.int_confocal_y_numsteps.setGeometry(QtCore.QRect(300, 450, 51, 22))
        self.int_confocal_y_numsteps.setMaximum(1000)
        self.int_confocal_y_numsteps.setObjectName("int_confocal_y_numsteps")
        self.dbl_confocal_acqtime = QtWidgets.QDoubleSpinBox(self.tab_Xsec)
        self.dbl_confocal_acqtime.setGeometry(QtCore.QRect(10, 450, 62, 22))
        self.dbl_confocal_acqtime.setDecimals(3)
        self.dbl_confocal_acqtime.setMaximum(1.0)
        self.dbl_confocal_acqtime.setSingleStep(0.005)
        self.dbl_confocal_acqtime.setProperty("value", 0.05)
        self.dbl_confocal_acqtime.setObjectName("dbl_confocal_acqtime")
        self.label_confocal_start = QtWidgets.QLabel(self.tab_Xsec)
        self.label_confocal_start.setGeometry(QtCore.QRect(190, 410, 47, 22))
        self.label_confocal_start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_confocal_start.setObjectName("label_confocal_start")
        self.label_confocal_stop = QtWidgets.QLabel(self.tab_Xsec)
        self.label_confocal_stop.setGeometry(QtCore.QRect(190, 430, 47, 22))
        self.label_confocal_stop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_confocal_stop.setObjectName("label_confocal_stop")
        self.label_confocal_numdivs = QtWidgets.QLabel(self.tab_Xsec)
        self.label_confocal_numdivs.setGeometry(QtCore.QRect(190, 450, 47, 22))
        self.label_confocal_numdivs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_confocal_numdivs.setObjectName("label_confocal_numdivs")
        self.label_confocal_x = QtWidgets.QLabel(self.tab_Xsec)
        self.label_confocal_x.setGeometry(QtCore.QRect(240, 390, 47, 13))
        self.label_confocal_x.setAlignment(QtCore.Qt.AlignCenter)
        self.label_confocal_x.setObjectName("label_confocal_x")
        self.label_confocal_y = QtWidgets.QLabel(self.tab_Xsec)
        self.label_confocal_y.setGeometry(QtCore.QRect(300, 390, 47, 13))
        self.label_confocal_y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_confocal_y.setObjectName("label_confocal_y")
        self.label_confocal_acqtime = QtWidgets.QLabel(self.tab_Xsec)
        self.label_confocal_acqtime.setGeometry(QtCore.QRect(10, 430, 71, 22))
        self.label_confocal_acqtime.setObjectName("label_confocal_acqtime")
        self.btn_confocal_save = QtWidgets.QPushButton(self.tab_Xsec)
        self.btn_confocal_save.setGeometry(QtCore.QRect(120, 400, 51, 23))
        self.btn_confocal_save.setObjectName("btn_confocal_save")
        self.chkbx_3D = QtWidgets.QCheckBox(self.tab_Xsec)
        self.chkbx_3D.setGeometry(QtCore.QRect(360, 450, 70, 17))
        self.chkbx_3D.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkbx_3D.setObjectName("chkbx_3D")
        self.btn_confocal_live = QtWidgets.QPushButton(self.tab_Xsec)
        self.btn_confocal_live.setGeometry(QtCore.QRect(130, 450, 51, 22))
        self.btn_confocal_live.setCheckable(True)
        self.btn_confocal_live.setObjectName("btn_confocal_live")
        self.label_confocal_live_avg = QtWidgets.QLabel(self.tab_Xsec)
        self.label_confocal_live_avg.setGeometry(QtCore.QRect(80, 430, 31, 22))
        self.label_confocal_live_avg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_confocal_live_avg.setObjectName("label_confocal_live_avg")
        self.int_confocal_live_avg = QtWidgets.QSpinBox(self.tab_Xsec)
        self.int_confocal_live_avg.setGeometry(QtCore.QRect(80, 450, 51, 22))
        self.int_confocal_live_avg.setKeyboardTracking(False)
        self.int_confocal_live_avg.setObjectName("int_confocal_live_avg")
        self.int_oct_frame_rate = QtWidgets.QSpinBox(self.tab_Xsec)
        self.int_oct_frame_rate.setGeometry(QtCore.QRect(420, 410, 51, 22))
        self.int_oct_frame_rate.setKeyboardTracking(False)
        self.int_oct_frame_rate.setMaximum(100)
        self.int_oct_frame_rate.setProperty("value", 20)
        self.int_oct_frame_rate.setObjectName("int_oct_frame_rate")
        self.label_oct_max_exp_time = QtWidgets.QLabel(self.tab_Xsec)
        self.label_oct_max_exp_time.setGeometry(QtCore.QRect(10, 420, 111, 22))
        self.label_oct_max_exp_time.setObjectName("label_oct_max_exp_time")
        self.tab_main.addTab(self.tab_Xsec, "")
        self.linein_sample_name = QtWidgets.QLineEdit(self.frame_main)
        self.linein_sample_name.setGeometry(QtCore.QRect(330, 10, 181, 20))
        self.linein_sample_name.setPlaceholderText("")
        self.linein_sample_name.setObjectName("linein_sample_name")
        self.label_sample_name = QtWidgets.QLabel(self.frame_main)
        self.label_sample_name.setGeometry(QtCore.QRect(288, 10, 47, 13))
        self.label_sample_name.setObjectName("label_sample_name")
        self.frame_toolbox = QtWidgets.QFrame(self.centralwidget)
        self.frame_toolbox.setGeometry(QtCore.QRect(520, 0, 441, 531))
        self.frame_toolbox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toolbox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toolbox.setObjectName("frame_toolbox")
        self.tab_toolbox = QtWidgets.QTabWidget(self.frame_toolbox)
        self.tab_toolbox.setGeometry(QtCore.QRect(10, 10, 425, 511))
        self.tab_toolbox.setObjectName("tab_toolbox")
        self.tab_diagnosis = QtWidgets.QWidget()
        self.tab_diagnosis.setObjectName("tab_diagnosis")
        self.glw_tracker = GraphicsLayoutWidget(self.tab_diagnosis)
        self.glw_tracker.setGeometry(QtCore.QRect(10, 10, 401, 461))
        self.glw_tracker.setObjectName("glw_tracker")
        self.tab_toolbox.addTab(self.tab_diagnosis, "")
        self.btn_debug = QtWidgets.QPushButton(self.centralwidget)
        self.btn_debug.setGeometry(QtCore.QRect(920, 0, 31, 23))
        self.btn_debug.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/bug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_debug.setIcon(icon)
        self.btn_debug.setCheckable(False)
        self.btn_debug.setObjectName("btn_debug")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionSin = QtWidgets.QAction(MainWindow)
        self.actionSin.setObjectName("actionSin")
        self.actionLorentzian = QtWidgets.QAction(MainWindow)
        self.actionLorentzian.setObjectName("actionLorentzian")
        self.actionGaussian = QtWidgets.QAction(MainWindow)
        self.actionGaussian.setObjectName("actionGaussian")
        self.actionExpDecay = QtWidgets.QAction(MainWindow)
        self.actionExpDecay.setObjectName("actionExpDecay")
        self.actionPowerDecay = QtWidgets.QAction(MainWindow)
        self.actionPowerDecay.setObjectName("actionPowerDecay")
        self.actionN15pol = QtWidgets.QAction(MainWindow)
        self.actionN15pol.setObjectName("actionN15pol")

        self.retranslateUi(MainWindow)
        self.tab_main.setCurrentIndex(0)
        self.tab_toolbox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_confocal_start.setText(_translate("MainWindow", "Start"))
        self.btn_confocal_stop.setText(_translate("MainWindow", "Stop"))
        self.label_confocal_start.setText(_translate("MainWindow", "start"))
        self.label_confocal_stop.setText(_translate("MainWindow", "stop"))
        self.label_confocal_numdivs.setText(_translate("MainWindow", "# step"))
        self.label_confocal_x.setText(_translate("MainWindow", "x"))
        self.label_confocal_y.setText(_translate("MainWindow", "y"))
        self.label_confocal_acqtime.setText(_translate("MainWindow", "Acq. Time (ms)"))
        self.btn_confocal_save.setText(_translate("MainWindow", "Save"))
        self.chkbx_3D.setText(_translate("MainWindow", "3D Scan"))
        self.btn_confocal_live.setText(_translate("MainWindow", "LIVE"))
        self.label_confocal_live_avg.setText(_translate("MainWindow", "# avg"))
        self.label_oct_max_exp_time.setText(_translate("MainWindow", "Max Exp Time xx ms"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_Xsec), _translate("MainWindow", "OCT Cross Section"))
        self.label_sample_name.setText(_translate("MainWindow", "Sample:"))
        self.tab_toolbox.setTabText(self.tab_toolbox.indexOf(self.tab_diagnosis), _translate("MainWindow", "Diagnostic"))
        self.actionSin.setText(_translate("MainWindow", "Sin"))
        self.actionLorentzian.setText(_translate("MainWindow", "Lorentzian"))
        self.actionGaussian.setText(_translate("MainWindow", "Gaussian"))
        self.actionExpDecay.setText(_translate("MainWindow", "Exp Decay"))
        self.actionPowerDecay.setText(_translate("MainWindow", "Power Decay"))
        self.actionN15pol.setText(_translate("MainWindow", "N15pol"))
from pyqtgraph import GraphicsLayoutWidget
import icon_rc
